<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.3.0</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.trivadis.kafkaws</groupId>
	<artifactId>spring-boot-cloudevents-producer</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>spring-boot-kafka-producer</name>
	<description>Kafka Producer project for Spring Boot using Kafka Transactions</description>
	<properties>
		<java.version>21</java.version>
		<spring-boot.version>3.3.0</spring-boot.version>
		<confluent.version>7.6.0</confluent.version>
		<avro.version>1.11.3</avro.version>
		<cloudevents.version>4.0.1</cloudevents.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.kafka</groupId>
			<artifactId>spring-kafka</artifactId>
		</dependency>

		<!-- Confluent Avro -->
		<dependency>
			<groupId>io.confluent</groupId>
			<artifactId>kafka-avro-serializer</artifactId>
			<version>${confluent.version}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.avro</groupId>
			<artifactId>avro</artifactId>
			<version>${avro.version}</version>
		</dependency>		

		<!-- CloudEvents SDK -->
		<dependency>
			<groupId>io.cloudevents</groupId>
			<artifactId>cloudevents-core</artifactId>
			<version>${cloudevents.version}</version>
		</dependency>
		<dependency>
			<groupId>io.cloudevents</groupId>
			<artifactId>cloudevents-kafka</artifactId>
			<version>${cloudevents.version}</version>
		</dependency>

		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<optional>true</optional>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.kafka</groupId>
			<artifactId>spring-kafka-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<mainClass>com.trivadis.kafkaws.OrdersApplication</mainClass>
				</configuration>
			</plugin>
			<!-- Avro code generation -->
			<plugin>
				<groupId>org.apache.avro</groupId>
				<artifactId>avro-maven-plugin</artifactId>
				<version>${avro.version}</version>
				<executions>
					<execution>
						<phase>generate-sources</phase>
						<goals><goal>schema</goal></goals>
						<configuration>
							<sourceDirectory>${project.basedir}/src/main/resources/avro</sourceDirectory>
							<outputDirectory>${project.build.directory}/generated-sources/avro</outputDirectory>
							<stringType>String</stringType>  <!-- use java.lang.String not CharSequence -->
						</configuration>
					</execution>
				</executions>
			</plugin>			
		</plugins>
	</build>
	<repositories>
		<repository>
			<id>confluent</id>
			<url>https://packages.confluent.io/maven/</url>
		</repository>
	</repositories>
</project>
