{"type":"record","name":"OrderStateEvent","namespace":"com.trivadis.kafkaws.order.avro.v1","fields":[{"name":"order","type":{"type":"record","name":"Order","fields":[{"name":"id","type":"long"},{"name":"productId","type":"long"},{"name":"productName","type":"string"},{"name":"quantity","type":"int"},{"name":"userId","type":"long"},{"name":"firstName","type":["null","string"],"default":null},{"name":"name","type":"string"},{"name":"address","type":{"type":"record","name":"Address","fields":[{"name":"street","type":"string"},{"name":"city","type":"string"},{"name":"zipCode","type":"string"},{"name":"country","type":"string","default":"CH"}]}}]}}]}