<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.3.3</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.trivadis.kafkaws</groupId>
	<artifactId>spring-boot-kafka-producer-avro-idl</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>spring-boot-kafka-producer</name>
	<description>Kafka Producer with Avro project for Spring Boot</description>
	<properties>
		<java.version>11</java.version>
		<confluent.version>8.0.0</confluent.version>
		<avro.version>1.12.0</avro.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.kafka</groupId>
			<artifactId>spring-kafka</artifactId>
		</dependency>

		<dependency>
			<groupId>org.apache.avro</groupId>
			<artifactId>avro</artifactId>
			<version>${avro.version}</version>
		</dependency>


		<dependency>
			<groupId>io.confluent</groupId>
			<artifactId>kafka-avro-serializer</artifactId>
			<version>${confluent.version}</version>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.kafka</groupId>
			<artifactId>spring-kafka-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.apache.avro</groupId>
				<artifactId>avro-maven-plugin</artifactId>
				<version>${avro.version}</version>
				<executions>
					<execution>
						<phase>generate-sources</phase>
						<goals>
							<goal>schema</goal>
							<goal>protocol</goal>
							<goal>idl-protocol</goal>
						</goals>
						<configuration>
							<stringType>String</stringType>
							<fieldVisibility>private</fieldVisibility>
							<sourceDirectory>src/main/schema</sourceDirectory>
						</configuration>
					</execution>
				</executions>
			</plugin>

			<plugin>
				<groupId>com.trivadis.plugins</groupId>
				<artifactId>avdl2avsc-maven-plugin</artifactId>
				<version>1.0.1-SNAPSHOT</version>
				<executions>
					<execution>
						<phase>generate-sources</phase>
						<goals>
							<goal>genschema</goal>
						</goals>
						<configuration>
							<inputAvdlDirectory>src/main/schema/avdl</inputAvdlDirectory>
							<outputSchemaDirectory>${basedir}/target/generated-sources/avro/schema
							</outputSchemaDirectory>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>io.confluent</groupId>
				<artifactId>kafka-schema-registry-maven-plugin</artifactId>
				<version>8.0.0</version>
				<configuration>
					<schemaRegistryUrls>
						<param>http://${DATAPLATFORM_IP}:8081</param>
					</schemaRegistryUrls>
				</configuration>
				<executions>

					<!-- ✅ Register schemas -->
					<execution>
						<id>register</id>
						<goals>
							<goal>register</goal>
						</goals>
						<configuration>
							<subjects>
								<pub.orderproc.order.state.v1-value>target/generated-sources/avro/schema/order/v1/OrderStateEvent.avsc</pub.orderproc.order.state.v1-value>
								<pub.orderproc.order.state.v2-value>target/generated-sources/avro/schema/order/v2/OrderStateEvent.avsc</pub.orderproc.order.state.v2-value>
							</subjects>
							<schemaTypes>
								<pub.orderproc.order.state.v1-value>AVRO</pub.orderproc.order.state.v1-value>
								<pub.orderproc.order.state.v2-value>AVRO</pub.orderproc.order.state.v2-value>
							</schemaTypes>
						</configuration>
					</execution>

					<!-- ✅ Download schemas -->
					<execution>
						<id>download</id>
						<goals>
							<goal>download</goal>
						</goals>
						<configuration>
							<outputDirectory>${project.basedir}/src/main/schema/avro</outputDirectory>
							<subjectPatterns>
							</subjectPatterns>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
	<repositories>
		<repository>
			<id>confluent</id>
			<url>https://packages.confluent.io/maven/</url>
		</repository>
	</repositories>
	<pluginRepositories>
		<pluginRepository>
			<id>confluent</id>
			<url>https://packages.confluent.io/maven/</url>
		</pluginRepository>
		<pluginRepository>
			<id>Trivadis Maven Repo</id>
			<url>https://github.com/TrivadisPF/avdl2avsc-maven-plugin/raw/mvn-repo/</url>
			<snapshots>
				<enabled>true</enabled>
				<updatePolicy>always</updatePolicy>
			</snapshots>
		</pluginRepository>
	</pluginRepositories>
</project>
