topic:
  name: test-spring-topic
  replication-factor: 3
  partitions: 12

spring:
  kafka:
    bootstrap-servers: ${DATAPLATFORM_IP}:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    properties:
      #partitioner.class: org.apache.kafka.clients.producer.internals.DefaultPartitioner
      #partitioner.class: org.apache.kafka.clients.producer.UniformStickyPartitioner
      #linger.ms: 100   # Time in milliseconds to wait before sending a batch
      #batch.size: 16384  # Batch size in bytes
      #partitioner.adaptive.partitioning.enable: true
